### ISSUE TITLE
Criteria overwrite

### ISSUE THREAD

**Issue by Mxrck** [atxy2k/essence#1]
Al parecer esta línea está causando que solo se pueda utilizar 1 criteria a la vez, ya que siempre se reescribe con `$otherModel` en vez de `$this->query` evitando que se puedan apilar criterias y devolviendo solo el último en el stack.

https://github.com/atxy2k/essence/blob/107f2d0904d2185e5ffe2492ba3bd26b839b1bc3/src/Infraestructure/Repository.php#L238

**Comment by atxy2k** [comment]
Se solucionó el error y está funcionando ahora.
